I/6685: Added helpers for debugging tables and preparing automatic tests.
ckeditor/ckeditor5-table pull request #312
Opened 2020-04-28 14:14 UTC by niegowski

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Added helpers for debugging tables and preparing automatic tests. Closes ckeditor/ckeditor5#6685.

---

### Additional information

2020-04-29 08:00 UTC, jodator requested changes
I'd remove those `eval` from code.

Other than that - it works really nice and will help us a lot with maintaining tables tests/samples.

2020-04-29 09:26 UTC, niegowski commented on tests/manual/tablemocking.js
> +		}
Intention for that textarea was to be able to put there any JS expression, not only static data, i.e.: 
```javascript
new Array( 10 ).fill( 0 ).map( () => new Array( 10 ).fill( 'x' ) )
```

2020-04-29 13:05 UTC, oleq commented on tests/manual/tablemocking.js
> +		}
I'm OK with `eval()` in this case.

1. KISS
2. This is a dev tool.
3. This will never land in npm.
4. This code will never be run by users.

2020-04-29 13:06 UTC, oleq commented on tests/manual/tablemocking.html
> +		/* noinspection Stylelint */
Yup, instead of disabling stylelint, let's have a proper `hsl()` here.

2020-04-29 13:19 UTC, niegowski commented on tests/manual/tablemocking.html
> +		/* noinspection Stylelint */
Already fixed 0bde76c.

2020-04-30 05:43 UTC, jodator reviewed
I think we've missed one `<meta>` tag - I don't recall if it is needed now.

2020-04-30 05:43 UTC, jodator commented on tests/_utils-tests/table-ascii-art.js
> +				]`
:+1:

2020-04-30 05:43 UTC, jodator commented on tests/manual/tablemocking.html
> +	<meta http-equiv="Content-Security-Policy" content="script-src 'self' https://ckeditor.com 'unsafe-inline' 'unsafe-eval'">
Is this header required? I've missed that previously.

2020-04-30 05:43 UTC, jodator commented on tests/manual/tablemocking.html
> +<style>
```suggestion
<style>
```

If the above is not needed :point\_up: .

2020-04-30 09:10 UTC, jodator approved these changes

2020-05-04 09:07 UTC, niegowski commented
Moved to https://github.com/ckeditor/ckeditor5/pull/6731.

2020-05-04 09:07 UTC, closed without merging